### ISSUE TITLE
Did you live on 22nd ave? 

### ISSUE THREAD

**Issue by howarth** [r-o-s-h-a-n/semisupervisedFL#10]
I have a wedding invitation for a Roshan Ramkeesoon that was sent to my apartment on 22nd Ave in Seattle. That you?

**Comment by r-o-s-h-a-n** [comment]
@howarth yes that is me! I miss that apartment. Who's the wedding for? maybe i already got the invite online. you can also email it to rramkeesoon93@gmail.com 
Thanks for reaching out!
